test ci-v2

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -19,3 +19,9 @@ jobs:
         cache: maven 
     - name: run test
       run: mvn test
+    - name: Show test error details
+      if: failure()
+      run: |
+        echo "=== Test error details ==="
+        cat target/surefire-reports/*.txt || echo "No .txt files found"
+        cat target/surefire-reports/*.xml || echo "No .xml files found"
